#!/usr/bin/env python3
"""Generate a one-line-per-decision index for each project in a Cairn repository.

Usage:
  index.py [REPOSITORY] [--check] [--stdout]

Writes projects/<project>/decisions-index.md. Only decisions whose status is
`valid` are listed, newest first. Each line has the date, the decision id, the
title, and the first sentence of the decision section. The decision file is
`decisions/<id>.md`.

  --check   write nothing; exit 1 if any index is missing or out of date
  --stdout  print the indexes instead of writing them

REPOSITORY defaults to the "repository" value in ~/.cairn/config.json (or the
file named by $CAIRN_CONFIG), then to the repository that contains this script.
Only the Python standard library is used.
"""

import argparse
import importlib.util
import re
import sys
from pathlib import Path

INDEX_NAME = "decisions-index.md"
SUMMARY_LIMIT = 140
DECISION_HEADINGS = ("Decision", "结论")
PLACEHOLDERS = ("to be validated", "待验证")

HEADER = (
    "<!-- Generated by scripts/index.py. Do not edit; run the script again. -->\n"
)


def load_validate():
    """Load the sibling validate.py so both scripts parse decisions the same way."""
    path = Path(__file__).resolve().with_name("validate.py")
    spec = importlib.util.spec_from_file_location("cairn_validate", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def first_sentence(body):
    """Return the first sentence of the decision section, shortened if long."""
    lines = body.split("\n")
    text = ""
    capture = False
    for line in lines:
        if line.startswith("## "):
            if capture:
                break
            capture = line[3:].strip() in DECISION_HEADINGS
            continue
        if capture:
            if not line.strip():
                if text:
                    break
                continue
            text += (" " if text else "") + line.strip()
    text = re.sub(r"\s+", " ", text).strip()
    if not text or text.lower().strip(". ") in PLACEHOLDERS:
        return ""
    match = re.search(r"[。！？]|[.!?](?=\s|$)", text)
    sentence = text[: match.end()] if match else text
    if len(sentence) > SUMMARY_LIMIT:
        sentence = sentence[: SUMMARY_LIMIT - 1].rstrip() + "…"
    return sentence


def title_of(body, fallback):
    for line in body.split("\n"):
        if line.startswith("# "):
            return line[2:].strip()
    return fallback


def render_project(validate, project_dir):
    """Return (index text, skipped paths, counts) for one project directory."""
    report = validate.Report()
    entries = []
    skipped = []
    omitted = 0
    decisions_dir = project_dir / "decisions"
    if decisions_dir.is_dir():
        for path in sorted(decisions_dir.glob("*.md")):
            result = validate.parse_decision(path, report)
            if result is None:
                skipped.append(path)
                continue
            fields, body = result
            status = fields.get("status")
            if status != "valid":
                omitted += 1
                continue
            entries.append(
                {
                    "id": path.stem,
                    "date": fields.get("decided_at", ""),
                    "title": title_of(body, path.stem),
                    "summary": first_sentence(body),
                }
            )
    entries.sort(key=lambda e: e["id"])
    entries.sort(key=lambda e: e["date"], reverse=True)

    lines = [HEADER, "# Decision index: %s\n" % project_dir.name]
    if entries:
        lines.append(
            "%d valid decision(s), newest first. Each line is `date id: title — first sentence`. "
            "Open `decisions/<id>.md` only when its line is relevant to the task.\n" % len(entries)
        )
        for e in entries:
            line = "- %s %s: %s" % (e["date"], e["id"], e["title"])
            if e["summary"]:
                line += " — %s" % e["summary"]
            lines.append(line)
    else:
        lines.append("No valid decisions yet.")
    if omitted:
        lines.append(
            "\n%d superseded or revoked decision(s) are not listed; they are kept in "
            "`decisions/` to explain history." % omitted
        )
    return "\n".join(lines) + "\n", skipped, {"listed": len(entries), "omitted": omitted}


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate Cairn decision indexes.")
    parser.add_argument("repository", nargs="?", help="path to the Cairn repository")
    parser.add_argument("--check", action="store_true", help="fail if an index is missing or stale")
    parser.add_argument("--stdout", action="store_true", help="print instead of writing files")
    args = parser.parse_args(argv)

    validate = load_validate()
    root = validate.resolve_repository(args.repository)
    projects_dir = root / "projects"
    if not projects_dir.is_dir():
        print("no projects/ directory found in %s" % root, file=sys.stderr)
        return 2

    stale = False
    for project in sorted(p for p in projects_dir.iterdir() if p.is_dir()):
        if project.name.startswith("_"):
            continue
        text, skipped, counts = render_project(validate, project)
        for path in skipped:
            print("%s: skipped (cannot be parsed; run validate.py)" % path.relative_to(root), file=sys.stderr)
        target = project / INDEX_NAME
        if args.stdout:
            print(text)
            continue
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if args.check:
            if current != text:
                stale = True
                print("%s is %s" % (target.relative_to(root), "missing" if current is None else "out of date"))
            continue
        if current != text:
            target.write_text(text, encoding="utf-8")
            print("Wrote %s (%d listed, %d omitted)" % (target.relative_to(root), counts["listed"], counts["omitted"]))
        else:
            print("Unchanged %s" % target.relative_to(root))
    if args.check and stale:
        print("Run: python3 %s" % Path(__file__).name, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
